### ISSUE TITLE
Putting the shutdown command in a settings field

### ISSUE THREAD

**Issue by srjacob999** [fmalekpour/OctoPrint-Gpioshutdown#10]
I am using the Octoprint Shutdown to trigger a timer to turn off my power supply (which supplies the Pi).  Right now, the timer is set for 15 seconds, which is adequate time for the Pi to fully shut down.  I have a shell script that turns on Pi pin 27, which triggers the timer, and then shuts down the Pi and printer power supply.  It works fine when I shut down Octoprint using the Octoprint shutdown.

Unfortunately, when I use this plugin and the push button to shut down Octoprint, the author has hard-coded the shutdown command within the plugin.  This makes it impossible to activate the shell script.

A useful modification to this plugin would be to have the shutdown command as an input variable in the setup screen like Octoprint has.  Alternatively, if there was some way to get access to the python code in the Pi, I could change the variable to my shell script.

Does anyone have any ideas?  I don't know Python very well, and I don't know if it worth forking off from the plug-in and making the modifications, or having the author do it.  If he did, I would buy him two beers.

Steve

**Comment by xrxca** [comment]
I think the command being an option would be useful (better than hard coding anyways)
Or (I don't know the Octoprint Internals so I may be wrong here) it may possible to trigger OctopPrint's shutdown process rather than just a sudo shutdwon... call?

**Comment by fmalekpour** [comment]
@srjacob999 implemented this. Thanks. Ver 1.0.3 released.
