### ISSUE TITLE
[Feature] LED for print status

### ISSUE THREAD

**Issue by ringo2k** [fmalekpour/OctoPrint-Gpioshutdown#13]
Hi, 

would it be a lot of work to add a second "LED" which turns on when a print started and off when the print finishes? 

I like to use it to turn additional lightning on for the camera and also a green "printing" sign. 

Regards
Ringo

**Comment by TeeVau** [comment]
Hey,

take a look at https://github.com/fmalekpour/OctoPrint-Cooldownfan

Seems to solve your request. Instead of controlling a fan you can connect an LED to the relay. Just use the normally open contact of the relay.

**Comment by ringo2k** [comment]
Hi, 

thanks for the answer! 
This should do the trick.
