### ISSUE TITLE
Typo in template 

### ISSUE THREAD

**Issue by xrxca** [fmalekpour/OctoPrint-Gpioshutdown#7]
There is a typo (well 2 actually) in the template file GPIOShutdown_settings.jinja2 which disable the use of GPIO 4
`<option value="4>GPIO 4</option>`
Should be 
`<option value="4">GPIO 4</option>`

(the current version is missing a quote in both GPIO 4 options)

**Comment by fmalekpour** [comment]
Fixed on main branch, will be published with next update.
